[project]
name = "01-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "lxml>=5.4.0",
    "pandas>=2.2.3",
    "polars>=1.29.0",
    "yfinance>=0.2.61",
]
